# Generated by Django 4.1.11 on 2023-09-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='istagram_link',
            new_name='instagram_link',
        ),
    ]
